### ISSUE TITLE
Macos/Windows vs Linux Port

### ISSUE THREAD

**Issue by mason-at-pieces** [Arindam200/pieces-readme-template#3]
Need to make sure that any user developing on Linux knows that their port is actually `5323` instead of `1000`, even though they shouldn't need to send any requests to it.

You mention `localhost:1000` in the `Testing Usage` section, I'd just change it to be something like this:

When your program starts, it needs to connect to Pieces OS to gain access to any functional data and to exchange information on `localhost:1000` (or `localhost:5323` for linux). Now that you have your `tracked_application` - lets get into the details.

**Comment by Arindam200** [comment]
Fixed!

**Comment by mason-at-pieces** [comment]
@Arindam200 I would look at https://docs.pieces.app/build/reference/typescript

I essentially want the getting started section of the repo to be similar to this, using the same example. Obviously doing this for each sdk 👍

**Comment by mason-at-pieces** [comment]
If you can update them in a pr, then I can check them out here and then we can get them all pushed 👍
